typography_spectrum: 0.9792884089984
content_rating:
  adult: true
color:
  brandStrength: 0.40453986218199134
  lightness: 0.8688171657267958
  saturation: 0.6642039509024471
  rhythmicContrast: 0.7619438637048006
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
layout_spectrum: 0.043716220650821924
author:
  name: Muhammed Al Maskary
  email: almaskary.production@gmail.com
  url: almaskary.photoshelter.com
name: Almaskari
navigation:
  - id: 92be8296-7d04-4a3d-af35-f77215f5a3eb
    url: >-
      2016-04-16-7-spring-road-trips-to-the-most-colorful-flowers-across-amer.html
    name: 7 spring road trips to the most colorful flowers across America
    type: content
title: were photography takes place
